### ISSUE TITLE
Peer dependencies cannot be met

### ISSUE THREAD

**Issue by philnash** [twilio-labs/twilio-style#105]
[npm version 7 now installs peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) and therefore needs the versions to resolve correctly.

`eslint-config-twilio` depends on:

* eslint-config-prettier@^7.0.0 which has a dependency on eslint >= 7
* eslint-plugin-sonarjs@^0.5.0 which has a peer dependency on eslint of "^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0"

These don't match and cause installs with npm 7 to fail unless the install is run with the `--force` or `--legacy-peer-deps` flats.

**Comment by ahcai** [comment]
@philnash looks like eslint-plugin-sonarjs@0.6.0 has eslint 7.0.0 as a peer dep so we can update this package and that should fix things

**Comment by ahcai** [comment]
this is fixed in v1.34.0!

**Comment by philnash** [comment]
Thanks!
