### ISSUE TITLE
Add Typescript style

### ISSUE THREAD

**Issue by TheSisb** [twilio-labs/twilio-style#20]
Hey! I was looking into trying this out on [Paste](https://github.com/twilio-labs/paste) but was held up by the lack of Typescript style rules.  As more of the org is moving towards Typescript on the front-end, it would be great to provide support for that.   Here's our current [eslint.rc](https://github.com/twilio-labs/paste/blob/master/.eslintrc.js) if it helps.

**Comment by ahcai** [comment]
@TheSisb We now have [TypeScript support](https://github.com/twilio-labs/twilio-style/tree/master/packages/eslint-config-twilio-ts) in v.1.10.0.
