### ISSUE TITLE
eslint-plugin-import - Error while loading rule 'import/no-unused-modules': Cannot read property 'path' of null

### ISSUE THREAD

**Issue by sabinasiddiqi** [twilio-labs/twilio-style#64]
I did a quick test run on our codebase using the instructions here for a typescript react app: https://github.com/twilio-labs/twilio-style/tree/master/packages/eslint-config-twilio-ts

And am getting this error:
```
TypeError: Error while loading rule 'import/no-unused-modules': Cannot read property 'path' of null
```

Seems like an existing issue for `eslint-plugin-import`:

https://github.com/benmosher/eslint-plugin-import/issues/1382

**Comment by sabinasiddiqi** [comment]
https://github.com/twilio-labs/twilio-style/blob/724c689043de1cb9fa32f15f26d2894f5971723d/packages/eslint-config-twilio/package.json#L41 - updating eslint-plugin-import to 2.20.20 should fix this: https://github.com/benmosher/eslint-plugin-import/compare/v2.19.0...master#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR32

**Comment by ahcai** [comment]
currently on `2.20.2` so this issue should've been fixed!
