### ISSUE TITLE
Add Sonarqube eslint plugin

### ISSUE THREAD

**Issue by vnguyen94** [twilio-labs/twilio-style#70]
https://github.com/SonarSource/eslint-plugin-sonarjs

There are many teams in Twilio that use Sonarqube, so it would have faster iteration cycles to know Sonar issues at pre-commit time.

**Comment by sabinasiddiqi** [comment]
+1

**Comment by vnguyen94** [comment]
fixed in https://github.com/twilio-labs/twilio-style/pull/100
