### ISSUE TITLE
Upgrade eslint to ^7.0.0

### ISSUE THREAD

**Issue by vnguyen94** [twilio-labs/twilio-style#83]
After recently upgrading our depedencies, getting some warnings for twilio-style peer dependencies:

```
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > eslint-config-twilio@1.23.0" has incorrect peer dependency "eslint@^6.8.0".
warning "eslint-config-twilio > eslint-config-twilio-base@1.23.0" has incorrect peer dependency "eslint@^6.8.0".
```

**Comment by ahcai** [comment]
@vnguyen94 we can upgrade this! also you are very welcome to open PRs if you'd like 😛

**Comment by vnguyen94** [comment]
@ahcai lemme see what i can do :P

**Comment by vnguyen94** [comment]
addressed by https://github.com/twilio-labs/twilio-style/pull/84 and released in https://github.com/twilio-labs/twilio-style/releases/tag/v1.25.0
